-- Supabase SQL Editor'da çalıştır. prompt_templates kolonunu ekler ve natural stilini günceller.
-- Kullanıcı "consistent reference face, hairstyle, and body" formatını kullanıyor ({face_description} yok).

ALTER TABLE public.photo_styles ADD COLUMN IF NOT EXISTS prompt_templates jsonb;

UPDATE public.photo_styles SET prompt_templates = '[
  {"category": "1. Portrait: The Hook", "prompt": "Create a vertical frame — size 2160×3840 pixels, 4K quality. Single full-height panel. Close-up portrait of a handsome man (consistent reference face, hairstyle, and body) standing outside a chic modern cafe. He wears a high-quality, fitted charcoal basic t-shirt. Direct eye contact with a subtle, mysterious smile. Golden hour sunlight illuminates the face, highlighting eye color and skin texture. Background is a creamy bokeh of city life. Shot on 85mm lens, f/1.4. Photorealistic, 8k, highly detailed pores, sharp focus on eyes, cinematic lighting."},
  {"category": "2. Social Proof: The Alpha", "prompt": "Create a vertical frame — size 2160×3840 pixels, 4K quality. Single full-height panel. Medium shot at a luxurious evening cocktail event. The character (consistent reference face, hairstyle, and body) wears a sharp navy suit with an open collar, holding a crystal glass. He is the center of attention, slightly elevated, while attractive friends (blurred in background) look at him laughing. Alpha body language, confident and relaxed. Warm ambient indoor lighting, flash photography style. Shot on 35mm lens, f/2.8. Hyper-realistic, social atmosphere, Old Money aesthetic."},
  {"category": "3. Passion: The Interesting Man", "prompt": "Create a vertical frame — size 2160×3840 pixels, 4K quality. Single full-height panel. Candid lifestyle shot of the character (consistent reference face, hairstyle, and body) working on an architectural sketch or playing an acoustic guitar in a loft studio. He wears a white shirt with sleeves rolled up, showcasing vascular forearms. He is not looking at the camera; intense focus on his craft. Soft natural window light falling from the side. Shot on 50mm lens. Texture-rich, authentic, messy but aesthetic environment. Photorealistic RAW photo."},
  {"category": "4. Adventure: The Prestige", "prompt": "Create a vertical frame — size 2160×3840 pixels, 4K quality. Single full-height panel. Wide-angle outdoor shot of the character (consistent reference face, hairstyle, and body) leaning on the railing of a luxury yacht or standing on a hotel balcony overlooking the Amalfi Coast. He wears a beige linen shirt unbuttoned at the top and premium sunglasses. Fit physique visible. Sunset lighting casting orange and blue hues. Shot on 24mm lens. High-end travel magazine style, aspirational vibe, 8k, volumetric clouds."},
  {"category": "5. Compassion: The Protector", "prompt": "Create a vertical frame — size 2160×3840 pixels, 4K quality. Single full-height panel. Eye-level shot of the character (consistent reference face, hairstyle, and body) sitting on autumn grass in a park, playing with a Golden Retriever dog. He wears a soft, textured cream cable-knit sweater. He is smiling genuinely with teeth, looking down at the dog. Warm, soft lighting, golden hour sun flares. Shot on 85mm lens. Emotional, trustworthy, safe atmosphere. Hyper-realistic fur and skin textures."},
  {"category": "6. Style: The Model", "prompt": "Create a vertical frame — size 2160×3840 pixels, 4K quality. Single full-height panel. Low-angle full-body fashion shot of the character (consistent reference face, hairstyle, and body) walking confidently in front of a minimalist concrete building. He wears a perfectly tailored smart-casual outfit: fitted trousers, Italian loafers, and a statement watch. One hand in pocket, one adjusting sunglasses. Dynamic walking pose. Sharp daylight, hard shadows, high contrast. Shot on 35mm lens, f/5.6. GQ editorial style, ultra-sharp details, 8k."}
]'::jsonb WHERE id = 'natural';
